### ISSUE TITLE
Request for an advice

### ISSUE THREAD

**Issue by borgogelli** [joestewart/robo-vagrant#1]
Hello

robo has a poor documentation. So I don't know how to write the loadTask trait for my tasks.
Reading your code, I see a difference with the official example.
That's your code:

```
trait loadTasks 
{

    public static function getVagrantServices()
    {
        return new SimpleServiceProvider(
            [
               ....
            ]
        );
    }

    protected function taskVagrantBox($pathToVagrant = null) {
        return new Box($pathToVagrant);
    }
 ....
}
```

Your loadTask traits return an object, like "return new Box()" (see above), while on the robo documentation and on robo source code i always find "return $this->task()", as below:

```
 protected function taskCompileAssets($path = null)
    {
        return $this->task(__FUNCTION__, $path);
    }
```

Please, can you give me some explanation

Thank you

Andrea

**Comment by joestewart** [comment]
This is a change for Robo >= 1.0.0.

See:  http://robo.li/changelog/#100
"Tasks' loadTasks traits must use $this->task('taskName'); instead of new TaskClass();"

The documentation has been updated for > 1.0.0

This role is compatible with the current stable 0.7.2

That documentation can be seen here:  https://github.com/consolidation-org/Robo/blob/0.7.2/docs/getting-started.md#tasks

Hope this helps.

**Comment by borgogelli** [comment]
Thank you Joe

I think that the mgration path to robo 1.0 is not so easy.
I have tried to use $this->task('taskName'); in my loadTasks trait but I get the error :
`Alias (taskName) is not being managed by the container`
I can resolve addign the following code:

```
$container = Robo\Config::getContainer();
$container->addServiceProvider(loadTasks::getMyServices());

```

but I don't know if it's a good solution. What do you think about ?

Regards

**Comment by joestewart** [comment]
Glad you got it working.  The current Getting Started doc ( http://robo.li/getting-started/ ) has a similar example.

> Services are registered with Robo as follows:
> 
> $container = \Robo\Config::getContainer();
> $container->addServiceProvider(\CompileAssets\loadTasks::getCollectionServices());
